### ISSUE TITLE
Complex number wrapper and examples 

### ISSUE THREAD

**Issue by hochunlin** [bmxam/PetscWrap.jl#11]
Hi, 

Thanks for this awesome Julia wrapper for the PETSc. It would help me a lot.

In my regime, instead of real, I deal with complex numbers. I tried to dig out how to use this Julia wrapper to solve complex problems. Unfortunately, I cannot figure it out. 

From https://github.com/bmxam/SlepcWrap.jl/blob/master/example/complex.jl#L8, I understood that `PetscScalar` should be complex datatype to use complex number problems. The default PETSc_jll.libpetsc would be real one. So, I set `libpetsc_path = PETSc_jll.libpetsc_Float64_Complex_Int64_path` in build.jl, and it showed that `PetscScalar` is ComplexF64. 

However, when I tried to modify the example `linear_system_fancy.jl` to validate whether it support the complex numbers. It gave me the wrong answer. For example 

```
n = 11
Δx = 1.0 / (n - 1)

A = create_matrix(comm; nrows_glo = n, ncols_glo = n, autosetup = true)
b = create_vector(comm; nrows_glo = n, autosetup = true)

b_start, b_end = get_range(b)

n_loc = length(b) ## Note that n_loc = b_end - b_start + 1...
b[b_start:b_end] = 1im * 2 * ones(n_loc)

A_start, A_end = get_range(A)
for i = A_start:A_end
    A[i, (i - 1):i] = 1im*[-1.0 1.0] / Δx
end

(b_start == 1) && (b[1] = 0.0)

# Assemble matrice and vector
assemble!(A)
assemble!(b)

# Set up the linear solver
ksp = create_ksp(A; autosetup = true)

# Solve the system
x = solve(ksp, b)

@show x
```

I would expect that it would give us the same x as I did not multiply 1im. However, I got a different and weird x.

and
```
M = create_matrix(comm; nrows_glo = 3, ncols_glo = 3, autosetup = true)
M_start, M_end = get_range(M)
I = [1, 1, 1, 2, 3]
J = [1, 3, 1, 3, 2]
V = [1+1im, 2+2im, 3+3im, 4+4im, 5+5im]
k = findall(x -> M_start <= x <= M_end, I) # just a trick to allow this example to run in parallel
set_values!(M, I[k], J[k], V[k], ADD_VALUES)
assemble!(M)
@show M
```
It cannot show the complex part of M.

Could you give me some direction on how to use PetscWrap.jl to solve complex numbers or provide a complex version in the example?

Many thanks!

**Comment by bmxam** [comment]
Hi,

I am almost always using `PetscWrap.jl` with complex numbers, so you can be confident that it works! However, I strongly advise you to install you own version of `petsc` and set your environment variables (`PETSC_DIR` and `PETSC_ARCH`) to link with your own version instead of relying on `Petsc_jll`.

Back to your problem. Here is what I did: I created a brand new julia project, added `PetscWrap` and `MPI`, then modified the `.julia/packages/PetscWrap/????/deps/build.jl` file to set `libpetsc_path = PETSc_jll.libpetsc_Float64_Complex_Int64_path` (as you did), then I built `PetscWrap.jl` again, quit julia, reran julia, and everything worked fine. In other terms, I did:
```
mkdir mwe
cd mwe
julia
] activate .
] add MPI PetscWrap
Ctrl + C # to quit REPL
# edit ~/.julia/packages/PetscWrap/????/deps/build.jl to set libpetsc_path = PETSc_jll.libpetsc_Float64_Complex_Int64_path
julia --project=.
] build
Ctrl + C
julia --project=. linear_system_fancy.jl
``` 
Without any further modification, the expected result is `x = [0, ..., 2]`. If I modified in this example `A` with `A[i, (i - 1):i] = im*[-1.0 1.0] / Δx` I do obtain the expected result `x = [0 + 0i, ..., 0 + 2i]`. Last, if I modify (like you did) both `A` and `b` with `b[b_start:b_end] = im * 2 * ones(n_loc)`, I obtain the expected result `x = [0, ..., 2]`.

A few questions:
* are you sure that you quit the REPL after the `] build` call to recompile `PetscWrap.jl` with complex numbers and then re-run julia?
* have you tried with your own install of PETSc?
* what is the `x` you obtain in your example (you mention a "weird x")?

**Comment by hochunlin** [comment]
Hi,

It is fantastic to hear that it worked well on your end! It gave me the confidence to test it on my machine.

Somehow, relying on Petsc_jll didn't yield the same results as yours.

I did
```
mkdir julia_test01
cd julia_test01
export JULIA_DEPOT_PATH=.
julia
] add https://github.com/bmxam/PetscWrap.jl.git # Note that I would encounter a missing library error if I used PetscWrap v0.2.1, so I added your latest PetscWrap v0.2.2
add MPI
Ctrl + C # to quit REPL
julia linear_system_fancy.jl
```
output
```
Vec Object: 1 MPI process
  type: seq
0.
0.2
0.4
0.6
0.8
1.
1.2
1.4
1.6
1.8
2.
x =
Mat Object: 1 MPI process
  type: seqaij
row 0: (0, 4.)  (2, 2.)
row 1: (2, 4.)
row 2: (1, 5.)
M =

```
Then I change the libpetsc_path to complex one.
```
Ctrl + C # to quit REPL
# edit packages/PetscWrap/SmOc3/deps/build.jl to set libpetsc_path = PETSc_jll.libpetsc_Float64_Complex_Int64_path
] build
Ctrl + C
julia linear_system_fancy.jl
```
output
```
Vec Object: 1 MPI process
  type: seq
inf.
inf.
inf.
inf.
inf.
inf.
inf.
inf.
inf.
inf.
inf.
x =
Mat Object: 1 MPI process
  type: seqaij
row 0: (0, 4.)  (2, 2.)
row 1: (2, 4.)
row 2: (1, 5.)

```
Instead of correct x, it gave me inf. 

Note if I used PetscWrap v0.2.1, the missing library error looks like 
```
/julia_test01/artifacts/52352a3b6f679226b157304cebd3d4d81539b305/lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.so.3.18"
libdmumpspar.so: cannot open shared object file: No such file or directory
```
 
I don't know if these two errors are specific to my machine or if something is in PETSc_jll. 

However, installing Petsc directly and setting my environment variables (PETSC_DIR and PETSC_ARCH) did work for the complex number! I really appreciate your suggestion and help! 

At last, I am wondering whether you plan to update your PetscWrap v0.2.2 version in JuliaRegistries. It would be great if users directly add and utilize your latest PetscWrap!

**Comment by bmxam** [comment]
Oh I see. You're right : using PetscWrap v0.2.1 we get some env errors. Since my env is already configured to link to MUMPS etc, I did no see this. I will try to publish PetscWrap v0.2.2, but it looks like you encountered a bug with it (with PETSC_jll at least) so it will demand some work.

**Comment by hochunlin** [comment]
Got it. Thank you! I am looking forward to the release of PetscWrap v0.2.2.

**Comment by bmxam** [comment]
Well I spent this evening looking at the error but it remains mysterious. Hence I am still hesitating between releasing a new version knowing that it doesn't work with Petsc_jll and complex (but is ok with user install of Petsc) or leaving things as is while the bug is present. Anyway it seems that the current release also leads to libpath problems so... I don't know.
